from exceptions.exceptional import convert, string_log

print(convert("33"))

print(convert("Hello"))

print(convert([1,2,3]))

print(string_log("ouch"))